### ISSUE TITLE
RestEase.HttpClientFactory .NET5 does not seem to register my typed client.

### ISSUE THREAD

**Issue by VictorioBerra** [canton7/RestEase#175]
## Error

```
❯ dotnet run
Building...
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: RestEaseWorker.Worker': Unable to resolve service for type 'RestEaseWorker.IPersonAPI' while attempting to activate 'RestEaseWorker.Worker'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: RestEaseWorker.Worker': Unable to resolve service for type 'RestEaseWorker.IPersonAPI' while attempting to activate 'RestEaseWorker.Worker'.        
 ---> System.InvalidOperationException: Unable to resolve service for type 'RestEaseWorker.IPersonAPI' while attempting to activate 'RestEaseWorker.Worker'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options) 
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options) 
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at RestEaseWorker.Program.Main(String[] args) in C:\Users\Desktop\RestEaseWorker\Program.cs:line 15
```

I am sure I am missing something silly, but I followed the directions here: https://github.com/canton7/RestEase#using-httpclientfactory

Repro: https://github.com/VictorioBerra/restease-httpclientfactory-issue

**Comment by canton7** [comment]
Weird. I don't think this is related to the source generator: it's failing to even call into RestEase.

Thanks for the full repro, I'll try and sort it out in the next few days or so.

**Comment by VictorioBerra** [comment]
This is not related sorry, this is a new issue for just `RestEase.HttpClientFactory`.

**Comment by canton7** [comment]
Ah, misread the title, my bad

**Comment by VictorioBerra** [comment]
Seems that the factory passed to `.AddTypedHttpClient(factory)` never gets invoked. But maybe I am missing something else.

Not that it matters I think, but `Microsoft.Extensions.Http` is pretty out of date https://github.com/canton7/RestEase/blob/master/src/RestEase.HttpClientFactory/RestEase.HttpClientFactory.csproj#L22 I tried bumping that to 5.0.0 and had no luck.

**Comment by VictorioBerra** [comment]
Maybe this is the issue? https://github.com/aspnet/HttpClientFactory/blob/master/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs#L422

According to the code here: https://github.com/canton7/RestEase/blob/master/src/RestEase.HttpClientFactory/HttpClientFactoryExtensions.cs#L171

it will attempt to `.AddTransient<object>(...` ?

**Comment by canton7** [comment]
Should be fixed in 1.5.2

**Comment by VictorioBerra** [comment]
Works.

**Comment by canton7** [comment]
Thanks!
