### ISSUE TITLE
Duplicate type name within an assembly

### ISSUE THREAD

**Issue by Suchiman** [canton7/RestEase#4]
Found in serverlog... probably not thread safe?
```
System.ArgumentException: Duplicate type name within an assembly.
   at System.Reflection.Emit.TypeBuilder.DefineType(RuntimeModule module, String fullname, Int32 tkParent, TypeAttributes attributes, Int32 tkEnclosingType, Int32[] interfaceTokens)
   at System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr)
   at RestEase.Implementation.ImplementationBuilder.BuildImplementationImpl(Type interfaceType) in c:\projects\restease\src\RestEase\Implementation\ImplementationBuilder.cs:Zeile 107.
   at RestEase.Implementation.ImplementationBuilder.<CreateImplementation>b__0[T](RuntimeTypeHandle key) in c:\projects\restease\src\RestEase\Implementation\ImplementationBuilder.cs:Zeile 87.
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at RestEase.Implementation.ImplementationBuilder.CreateImplementation[T](IRequester requester) in c:\projects\restease\src\RestEase\Implementation\ImplementationBuilder.cs:Zeile 90.
   at RestClient.For<T>(...)
```

**Comment by canton7** [comment]
Looks like I forgot the very important note in the Remarks section of `ConcurrentDictionary.GetOrAdd`

> If you call GetOrAdd simultaneously on different threads, addValueFactory may be called multiple times, but its key/value pair might not be added to the dictionary for every call. 

I'll get this fixed up pronto, apologies!
