### ISSUE TITLE
Underlying Connection Closed - How to Debug?

### ISSUE THREAD

**Issue by leonisa** [canton7/RestEase#45]
Hi,

I am trying to run some simple tests against the Asana API and am getting a connection closed exception. The call has been tested in ARC for Chrome and translating it into RestEase syntax should be trivial but it does not work (very very simple GET request). I can't seem to drill down into any useful info to work out what is failing - the response object never gets populated as it never gets that far.

Can I somehow examine the concatenated URL / headers / payload that is being sent just before the request is made etc. to see if there is an obvious syntax issue?

> Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestWithResponseAsync>d__28`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

>

**Comment by canton7** [comment]
Fiddler is my first go-to for something like this: you can see exactly what's going down the wire. You could also use a RequestModifier (see the README).

**Comment by leonisa** [comment]
I think I have found it. I am using a legacy console app. Although it has been set to compile to 4.5 for a long time it looks like the default SSL settings are legacy. I got it to work by using this
`   System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
                 `

before init of the RestEase object

**Comment by canton7** [comment]
Cool, thanks for the update.
